project:
  type: website
  output-dir: docs

website:
  title: "claramchae.github.io"
  navbar:
    background: "#A2D909"
    foreground: "#484F32"
    left:
      - href: about.qmd
        text: About
      - text: Data Viz
        menu:
          - href: country.qmd
            text: Country Music Lyrics
          - href: amazon.qmd
            text: Amazon Annual Reports

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  echo: false
  warning: false
  message: false
  
  

